spring:
  main:
     banner-mode: "off"
  application:
    name: mashup-service
  social:
    twitter:
      app-id: aHSBLM2sUk9qN826xP5btJCyj
      app-secret: 5fJJfLu1HajaQ2ybmlBlE6DsGY5e1FMO7CGZLBsa8uKVMkmEuU
external_url: https://api.github.com/search/repositories