spring:
  main:
     banner-mode: "off"
  application:
    name: mashup-service
  social:
    twitter:
      app-id: ${TWITTER_APP_ID}
      app-secret: ${TWITTER_APP_SECRET}
      ratelimit:  11
github_repository_search_endpoint: https://api.github.com/search/repositories
