spring:
  main:
     banner-mode: "off"
  application:
    name: mashup-service
  social:
    twitter:
      app-id: __NA__
      app-secret: __NA__
      ratelimit:  11
github_repository_search_endpoint: https://api.github.com/search/repositories
